export enum MenuTestIDEnum {
  MOBILE_BUTTON = "MOBILE_BUTTON",
  BACKDROP_BODY = "BACKDROP_BODY",
  MENU_CONTAINER = "MENU_CONTAINER",
  MENU_NAVBAR = "MENU_NAVBAR",
  SWITCH_DARK_MODE = "SWITCH_DARK_MODE",
}
